#!/usr/bin/env python3
import argparse
import datetime
import hashlib
import json
import sys
from pathlib import Path


DDL_DEFAULT_PATH = Path(__file__).parent / "schema.sql"
STDLIB_MODULES = set(getattr(sys, "stdlib_module_names", []))


def load_schema(cur, schema_file: Path):
    with schema_file.open("r", encoding="utf-8") as fh:
        cur.execute(fh.read())

def iter_records(input_file: Path):
    with input_file.open("r", encoding="utf-8") as fh:
        for line_no, raw in enumerate(fh, start=1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                yield line_no, json.loads(raw)
            except json.JSONDecodeError:
                continue


def normalize_package_name(raw_pkg):
    if not isinstance(raw_pkg, str):
        return None
    pkg = raw_pkg.strip()
    if not pkg:
        return None
    top_level = pkg.split(".", 1)[0]
    if top_level.startswith("_"):
        return None
    if top_level in STDLIB_MODULES:
        return None
    return top_level


def main():
    parser = argparse.ArgumentParser(description="Upload users-only conda telemetry into Postgres")
    parser.add_argument("--db", required=True, help="Postgres connection string")
    parser.add_argument("--schema-file", default=str(DDL_DEFAULT_PATH), help="Schema SQL file path")
    parser.add_argument(
        "--cleanup-existing-packages",
        action="store_true",
        help="Delete existing stdlib and underscore-prefixed package rows before ingest",
    )
    parser.add_argument("input_file", help="Flattened ndjson generated by dump_conda_telemetry.py")
    args = parser.parse_args()

    input_file = Path(args.input_file)
    schema_file = Path(args.schema_file)

    import psycopg2
    from psycopg2.extras import execute_batch

    BATCH_SIZE = 500

    with psycopg2.connect(args.db) as conn:
        with conn.cursor() as cur:
            load_schema(cur, schema_file)

            deleted_existing_packages = 0
            if args.cleanup_existing_packages:
                cur.execute(
                    """
                    DELETE FROM conda_env_packages
                    WHERE left(package_name, 1) = '_'
                       OR package_name = ANY(%s)
                    """,
                    (sorted(STDLIB_MODULES),),
                )
                deleted_existing_packages = cur.rowcount

        conn.commit()

        total_sessions = 0
        total_packages = 0
        bad_rows = 0
        rows_seen = 0
        session_batch = []
        package_batch = []

        def flush(cur):
            nonlocal total_sessions, total_packages
            if session_batch:
                execute_batch(
                    cur,
                    """
                    INSERT INTO conda_env_sessions (
                        event_hash,
                        event_time,
                        env_name,
                        user_id,
                        pid,
                        sys_executable,
                        sys_prefix,
                        source_file,
                        source_line
                    ) VALUES (%s, %s::timestamptz, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (event_hash) DO NOTHING
                    """,
                    session_batch,
                    page_size=BATCH_SIZE,
                )
                total_sessions += len(session_batch)
                session_batch.clear()
            if package_batch:
                execute_batch(
                    cur,
                    """
                    INSERT INTO conda_env_packages (event_hash, package_name)
                    VALUES (%s, %s)
                    ON CONFLICT (event_hash, package_name) DO NOTHING
                    """,
                    package_batch,
                    page_size=BATCH_SIZE,
                )
                total_packages += len(package_batch)
                package_batch.clear()

        with conn.cursor() as cur:
            for _, record in iter_records(input_file):
                rows_seen += 1
                try:
                    raw_ts = str(record.get("timestamp") or "").strip()
                    if not raw_ts:
                        bad_rows += 1
                        continue

                    # Parse ISO timestamp variants and normalize to UTC day bucket.
                    ts = datetime.datetime.fromisoformat(raw_ts.replace("Z", "+00:00"))
                    day = ts.astimezone(datetime.timezone.utc).date().isoformat()
                    env_name = record.get("env_name")
                    user_id = record.get("user_id")

                    event_hash = hashlib.sha256(
                        json.dumps(
                            {"day": day, "env_name": env_name, "user_id": user_id},
                            sort_keys=True,
                            separators=(",", ":"),
                        ).encode("utf-8")
                    ).hexdigest()

                    session_batch.append(
                        (
                            event_hash,
                            f"{day}T00:00:00+00:00",
                            env_name,
                            user_id,
                            None,
                            None,
                            None,
                            record.get("source_file"),
                            None,
                        )
                    )
                    seen_packages = set()
                    for pkg in record.get("packages", []):
                        normalized_pkg = normalize_package_name(pkg)
                        if not normalized_pkg or normalized_pkg in seen_packages:
                            continue
                        seen_packages.add(normalized_pkg)
                        package_batch.append((event_hash, normalized_pkg))
                except Exception:
                    bad_rows += 1

                if len(session_batch) >= BATCH_SIZE:
                    flush(cur)
                    conn.commit()
                    if total_sessions % 10000 < BATCH_SIZE:
                        print(f"Progress: {total_sessions} sessions inserted...", flush=True)

            flush(cur)

            cur.execute(
                """
                INSERT INTO conda_env_ingest_runs (input_file, rows_in_file, rows_parsed, bad_rows)
                VALUES (%s, %s, %s, %s)
                """,
                (str(input_file), rows_seen, total_sessions, bad_rows),
            )

        conn.commit()

    summary = {
        "input_file": str(input_file),
        "mode": "users_only",
        "rows_parsed": total_sessions,
        "packages_inserted": total_packages,
        "packages_deleted_existing": deleted_existing_packages,
        "bad_rows": bad_rows,
    }
    print(json.dumps(summary, sort_keys=True))


if __name__ == "__main__":
    main()
